/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedColecaoIndexRouteImport } from './routes/_authenticated/colecao/index'
import { Route as AuthenticatedColecaoNovaRouteImport } from './routes/_authenticated/colecao/nova'
import { Route as AuthenticatedPecaIdRouteImport } from './routes/_authenticated/peca/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColecaoIndexRoute =
  AuthenticatedColecaoIndexRouteImport.update({
    id: '/colecao/',
    path: '/colecao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColecaoNovaRoute =
  AuthenticatedColecaoNovaRouteImport.update({
    id: '/colecao/nova',
    path: '/colecao/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPecaIdRoute = AuthenticatedPecaIdRouteImport.update({
  id: '/peca/$id',
  path: '/peca/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/colecao/nova': typeof AuthenticatedColecaoNovaRoute
  '/peca/$id': typeof AuthenticatedPecaIdRoute
  '/colecao/': typeof AuthenticatedColecaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/colecao/nova': typeof AuthenticatedColecaoNovaRoute
  '/peca/$id': typeof AuthenticatedPecaIdRoute
  '/colecao': typeof AuthenticatedColecaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/colecao/nova': typeof AuthenticatedColecaoNovaRoute
  '/_authenticated/peca/$id': typeof AuthenticatedPecaIdRoute
  '/_authenticated/colecao/': typeof AuthenticatedColecaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/painel' | '/colecao/nova' | '/peca/$id' | '/colecao/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/painel' | '/colecao/nova' | '/peca/$id' | '/colecao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/painel'
    | '/_authenticated/colecao/nova'
    | '/_authenticated/peca/$id'
    | '/_authenticated/colecao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colecao/': {
      id: '/_authenticated/colecao/'
      path: '/colecao'
      fullPath: '/colecao/'
      preLoaderRoute: typeof AuthenticatedColecaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colecao/nova': {
      id: '/_authenticated/colecao/nova'
      path: '/colecao/nova'
      fullPath: '/colecao/nova'
      preLoaderRoute: typeof AuthenticatedColecaoNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/peca/$id': {
      id: '/_authenticated/peca/$id'
      path: '/peca/$id'
      fullPath: '/peca/$id'
      preLoaderRoute: typeof AuthenticatedPecaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedColecaoNovaRoute: typeof AuthenticatedColecaoNovaRoute
  AuthenticatedPecaIdRoute: typeof AuthenticatedPecaIdRoute
  AuthenticatedColecaoIndexRoute: typeof AuthenticatedColecaoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedColecaoNovaRoute: AuthenticatedColecaoNovaRoute,
  AuthenticatedPecaIdRoute: AuthenticatedPecaIdRoute,
  AuthenticatedColecaoIndexRoute: AuthenticatedColecaoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
